"""Add confidence range constraints

Revision ID: 84e82e522d2d
Revises: 5edeccc2e4d9
Create Date: 2026-08-30 20:21:25.242668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e82e522d2d'
down_revision: Union[str, Sequence[str], None] = '5edeccc2e4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('chk_policy_confidence_range', 'policies', 'min_confidence >= 0 AND min_confidence <= 1')
    op.create_check_constraint('chk_recovery_prob_range', 'recovery_cases', 'recovery_probability >= 0 AND recovery_probability <= 1')
    op.create_check_constraint('chk_decision_confidence_range', 'recovery_decisions', 'confidence >= 0 AND confidence <= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_decision_confidence_range', 'recovery_decisions', type_='check')
    op.drop_constraint('chk_recovery_prob_range', 'recovery_cases', type_='check')
    op.drop_constraint('chk_policy_confidence_range', 'policies', type_='check')
    # ### end Alembic commands ###
