"""add approval_status to recovery_case

Revision ID: a15a0a689b7a
Revises: 84e82e522d2d
Create Date: 2026-09-01 17:06:39.779925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15a0a689b7a'
down_revision: Union[str, Sequence[str], None] = '84e82e522d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('approval_status', sa.String(length=50), nullable=True))
    op.add_column('recovery_cases', sa.Column('approved_by', sa.String(length=100), nullable=True))
    op.add_column('recovery_cases', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recovery_cases', sa.Column('rejected_by', sa.String(length=100), nullable=True))
    op.add_column('recovery_cases', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recovery_cases', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'rejection_reason')
    op.drop_column('recovery_cases', 'rejected_at')
    op.drop_column('recovery_cases', 'rejected_by')
    op.drop_column('recovery_cases', 'approved_at')
    op.drop_column('recovery_cases', 'approved_by')
    op.drop_column('recovery_cases', 'approval_status')
    # ### end Alembic commands ###
