"""phase9

Revision ID: f80350304af3
Revises: de8b77fad989
Create Date: 2026-09-02 06:56:10.277541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f80350304af3'
down_revision: Union[str, Sequence[str], None] = 'de8b77fad989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('assigned_strategy', sa.String(length=50), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('recovered_amount', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'recovery_case_id', name='uq_experiment_case_assignment')
    )
    op.create_index(op.f('ix_experiment_assignments_experiment_id'), 'experiment_assignments', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_recovery_case_id'), 'experiment_assignments', ['recovery_case_id'], unique=False)
    op.add_column('recovery_cases', sa.Column('priority_level', sa.String(length=20), nullable=True))
    op.add_column('recovery_cases', sa.Column('expected_recovery_value', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_recovery_cases_priority_level'), 'recovery_cases', ['priority_level'], unique=False)
    op.alter_column('recovery_cases', 'priority_score', type_=sa.Numeric(precision=20, scale=5), existing_type=sa.Numeric(precision=10, scale=5))
    op.add_column('recovery_decisions', sa.Column('priority_score', sa.Numeric(precision=20, scale=5), nullable=True))
    op.add_column('recovery_decisions', sa.Column('policy_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recovery_decisions', sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_decisions', 'reason_codes')
    op.drop_column('recovery_decisions', 'policy_checks')
    op.drop_column('recovery_decisions', 'priority_score')
    op.alter_column('recovery_cases', 'priority_score', type_=sa.Numeric(precision=10, scale=5), existing_type=sa.Numeric(precision=20, scale=5))
    op.drop_index(op.f('ix_recovery_cases_priority_level'), table_name='recovery_cases')
    op.drop_column('recovery_cases', 'expected_recovery_value')
    op.drop_column('recovery_cases', 'priority_level')
    op.drop_index(op.f('ix_experiment_assignments_recovery_case_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_experiment_id'), table_name='experiment_assignments')
    op.drop_table('experiment_assignments')
    # ### end Alembic commands ###
